### ISSUE TITLE
IDが短いとグロナビのレイアウトが崩れる

### ISSUE THREAD

**Issue by s4na** [kumaGoro95/ExpensesApp#90]
突然すみません。
デザイン崩れに気づいたのでご報告させていただきます。🙏

以下のように、ユーザーのIDが短いとレイアウトが崩れてしまうみたいです。

対象方法としては、一定の値より小さくなって欲しくない値に `min-width` を設定してあげるのが良さそうかと思います。
以上、ご確認のほどよろしくお願いします。

## ユーザーIDが短い場合

<img width="257" alt="Screen Shot 2021-03-13 at 22 11 06" src="https://user-images.githubusercontent.com/42843963/111031148-6c563480-8449-11eb-89da-f9a012ccfce2.png">

<img width="283" alt="Screen Shot 2021-03-13 at 22 11 01" src="https://user-images.githubusercontent.com/42843963/111031145-6b250780-8449-11eb-8d8d-c02e40ed8a7e.png">

## ユーザーIDが長い場合

<img width="273" alt="Screen Shot 2021-03-13 at 22 11 26" src="https://user-images.githubusercontent.com/42843963/111031150-6ceecb00-8449-11eb-86c9-3110b2b1553d.png">
<img width="249" alt="Screen Shot 2021-03-13 at 22 11 31" src="https://user-images.githubusercontent.com/42843963/111031158-6f512500-8449-11eb-9158-4a602cdfd108.png">

**Comment by kumaGoro95** [comment]
@s4na 

初めまして。
ご指摘いただき、ありがとうございます！

自分でも確認してみたところ、ユーザーIDに半角文字が含まれているとレイアウトの崩れが出ていることがわかりました...
ご教示いただいた通り、ヘッダーのユーザー名に`min-width`を設定し、ユーザーIDが最も短い場合でもレイアウトの崩れが出ないよう修正致しました！

修正方法まで細かく教えていただいたおかげで、すぐに対応することができました。
このたびはありがとうございました。🙇‍♀️

# 修正結果

![スクリーンショット (43)](https://user-images.githubusercontent.com/68217595/111032252-9c540680-844e-11eb-82ff-77760429102e.png)

![スクリーンショット (42)](https://user-images.githubusercontent.com/68217595/111032249-9a8a4300-844e-11eb-972d-c408cb01badb.png)

**Comment by s4na** [comment]
修正を確認したのでCloseします。

転職頑張って下さい👍
